baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 10

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 0

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true
  

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.en]
    languageName = "English"
    title = "__namc"
    subtitle = ""
    keywords = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    copyright = "Blog by Namrata Chaudhary"

    [languages.en.params.logo]
      logoText = "__namc"
      logoHomeLink = "/"
      
     
[[params.soicial]]
icon = "github"
url = "https://github.com/namratachaudhary/"
