baseURL = "/"
languageCode = "en-us"
title = "Namc's blog"
theme = "yinyang"
DefaultContentLanguage = "en"
paginate = 20

[author]
  name = "__namc"
  homepage = "https://namc.in/"

[params]
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://namc.in"

[[params.socials]]
name = "Github"
link = "https://github.com/namratachaudhary"

[[params.socials]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/namrata-c-542b8a56/"

# Enable tags.
[taxonomies]
   tag = "tags"